#include "minishell.h"

void	loop_minishell(t_env *env);

void	bkolani(char *argv[], char *envp[])
{
	(void)argv;
	(void)envp;
	(void)argv;
	(void)envp;
	t_env *env;

	env = handle_env(envp);
	// t_chain *adj1 = ft_malloc_bkol(sizeof(t_chain), ALLOCATE);
	// t_chain *adj2 = ft_malloc_bkol(sizeof(t_chain), ALLOCATE);
	// t_chain *adj3 = ft_malloc_bkol(sizeof(t_chain), ALLOCATE);
	t_chain *data =  ft_malloc_bkol(sizeof(t_chain), ALLOCATE);
	// adj1->file = "adj1";
	// adj1->type = REDIR_OUT;
	// adj1->next = adj2;
	// adj2->file = "adj2";
	// adj2->type = REDIR_OUT;
	// adj2->next = adj3;
	// adj3->file = "adj3";
	// adj3->type = REDIR_APPEND;
	// adj3->next = NULL;
	// t_chain *blk1 = ft_malloc_bkol(sizeof(t_chain), ALLOCATE);
	// t_chain *blk2 = ft_malloc_bkol(sizeof(t_chain), ALLOCATE);
	// t_chain *blk3 = ft_malloc_bkol(sizeof(t_chain), ALLOCATE);
	// blk1->file = "blk1";
	// blk1->type = REDIR_OUT;
	// blk1->next = blk2;
	// blk2->file = "blk2";
	// blk2->type = REDIR_OUT;
	// blk2->next = blk3;
	// blk3->file = "blk3";
	// blk3->type = REDIR_APPEND;
	// blk3->next = NULL;
	// data->adj_f = adj1;
	// data->blk_f = blk1;
	// data->argv = NULL;
	// data->next = NULL;
	// pwd(data);
	// print_env_vars(env);
	t_argv *args1 = ft_malloc_bkol(sizeof(t_argv), ALLOCATE);
	args1->content = "EOF\\";
	args1->next = NULL;
	// t_argv *args2 = ft_malloc_bkol(sizeof(t_argv), ALLOCATE);
	// t_argv *args3 = ft_malloc_bkol(sizeof(t_argv), ALLOCATE);
	// t_argv *args4 = ft_malloc_bkol(sizeof(t_argv), ALLOCATE);
	// t_chain *data_unset =  ft_malloc_bkol(sizeof(t_chain), ALLOCATE);
	// args1->content = "NAME=kol";
	// args1->next = args2;
	// args2->content = "NAME2=biman";
	// args2->next = args3;
	// args3->content = "..";
	// args3->next = NULL;
	// data->argv = args1;
	// data->adj_f = adj1;
	// data->blk_f = blk1;
	// data->next = NULL;
	// export(env, data);
	// mini_env(env, data);
	// pwd(data);
	// echo(data);
	// mini_exit(data);
	// cd(env, data);
	// args4->content = "NAME2";
	// args4->next = NULL;
	// data_unset->argv = args4;
	// data->adj_f = adj1;
	// data->blk_f = blk1;
	// data_unset->next = NULL;
	// unset(env, data_unset);
	// mini_env(env, NULL);
	data->argv = args1;
	data->next = NULL;
	here_doc(data);
	(void)env;
}
